# Generated by Django 4.2.7 on 2026-02-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Anomalies',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('blood_pressure_systolic', models.IntegerField(help_text='Systolic blood pressure in mmHg')),
                ('blood_pressure_diastolic', models.IntegerField(help_text='Diastolic blood pressure in mmHg')),
                ('blood_glucose', models.DecimalField(decimal_places=2, help_text='Blood glucose level in mg/dL', max_digits=5)),
                ('heart_rate', models.IntegerField(help_text='Heart rate in bpm')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('steps', models.IntegerField(default=0, help_text='Number of steps taken daily')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
