# Generated by Django 4.2.7 on 2026-02-07 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health_metrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthmetric',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='health_metrics.healthmetric'),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='healthmetric',
            index=models.Index(fields=['user', 'recorded_at'], name='health_metr_user_id_235189_idx'),
        ),
    ]
